name: food
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  toastification: ^3.0.3
  shared_preferences: ^2.5.3
  animate_do: ^4.2.0
  smooth_page_indicator: ^1.2.1
  font_awesome_flutter: ^10.9.1
  pinput: ^5.0.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  google_sign_in: ^6.2.1
  permission_handler: ^12.0.1
  flutter_facebook_auth: ^7.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

# setting up flutter launcher icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/food_delivery_app.png"  
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
